Repository decent-chat/spec, pull requests merged in 2018-05, with the labels that each got.

#6 Endpoints for giving and taking roles
  doc.md
Labels: proposal

#11 Automatic Table of Contents generation
  doc.md
  makefile
  spec.md
Labels: formatting

#12 Add 'grantRoles' permission
  doc.md
Labels: proposal

#14 Define internal roles and limit channel-specific permission overrides
  doc.md
  spec.md
Labels: correction

#16 Make new roles less prioritized than the creator's highest role
  doc.md
Labels: proposal

#17 Be strict about which roles can be reordered
  doc.md
Labels: proposal
